// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn8MrOXZK7aJAgUOsBElb1F7yreHpfRdQ',
    appId: '1:710542392207:web:7b425fbff1928c2d0ea9fa',
    messagingSenderId: '710542392207',
    projectId: 'depthblue-90517',
    authDomain: 'depthblue-90517.firebaseapp.com',
    storageBucket: 'depthblue-90517.appspot.com',
    measurementId: 'G-PN4NN4Q100',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDQssVtM5_vRN5mjUoFYGfdow_TF40FgQ',
    appId: '1:710542392207:android:e6ceb51e959b24850ea9fa',
    messagingSenderId: '710542392207',
    projectId: 'depthblue-90517',
    storageBucket: 'depthblue-90517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKjrAmjvNQGaXjsFy1XTx1__1EgKCLgwM',
    appId: '1:710542392207:ios:35d436d50faee6e80ea9fa',
    messagingSenderId: '710542392207',
    projectId: 'depthblue-90517',
    storageBucket: 'depthblue-90517.appspot.com',
    iosBundleId: 'com.depthblue.depthblue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKjrAmjvNQGaXjsFy1XTx1__1EgKCLgwM',
    appId: '1:710542392207:ios:1c05afd5826616630ea9fa',
    messagingSenderId: '710542392207',
    projectId: 'depthblue-90517',
    storageBucket: 'depthblue-90517.appspot.com',
    iosBundleId: 'com.depthblue.depthblue.RunnerTests',
  );
}
